"""Command-line interface for py-yt-video-downloader.

The CLI uses argparse to provide a dependency-light, professional command-line
experience. It validates malformed commands early, prints friendly recovery tips,
and delegates successful requests to the yt-dlp backed downloader module.
"""

from __future__ import annotations

import argparse
import sys
import traceback
from collections.abc import Sequence
from typing import NoReturn

from . import __version__
from .downloader import build_request, download
from .errors import DownloaderError
from .validation import SUPPORTED_FORMATS, SUPPORTED_QUALITIES

EXAMPLES = """
Examples:
  py-yt-video-downloader https://youtu.be/VIDEO_ID --format mp4 --output "C:\\Users\\Tanner\\Downloads"
  py-yt-video-downloader https://www.youtube.com/watch?v=VIDEO_ID -f mp3 -o ./downloads
  py-yt-video-downloader https://youtu.be/VIDEO_ID -o ./downloads --quality 720p --overwrite

Tooltips:
  * Use --format mp4 for video or --format mp3 for audio-only output.
  * MP3 conversion requires FFmpeg to be installed and available on PATH.
  * The output directory is created automatically when possible.
""".strip()


class FriendlyArgumentParser(argparse.ArgumentParser):
    """ArgumentParser subclass that prints examples with malformed commands.

    Args:
        *args: Positional arguments forwarded to ``argparse.ArgumentParser``.
        **kwargs: Keyword arguments forwarded to ``argparse.ArgumentParser``.
    """

    def error(self, message: str) -> NoReturn:
        """Print a friendly parse error, help text, and examples before exiting.

        Args:
            message: Error message generated by argparse.

        Returns:
            This method never returns because it exits with status code 2.

        Raises:
            SystemExit: Always raised with exit code 2 for malformed commands.
        """
        self.print_usage(sys.stderr)
        print(f"\nCommand problem: {message}", file=sys.stderr)
        print("\nHow to fix it:", file=sys.stderr)
        print(EXAMPLES, file=sys.stderr)
        raise SystemExit(2)


def create_parser() -> argparse.ArgumentParser:
    """Create the CLI argument parser.

    Args:
        None.

    Returns:
        Configured ``argparse.ArgumentParser`` with all supported options.
    """
    parser = FriendlyArgumentParser(
        prog="py-yt-video-downloader",
        description=(
            "Download a YouTube video as MP4 or extract audio as MP3 using yt-dlp. "
            "Only download content you have the right to download."
        ),
        epilog=EXAMPLES,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "url",
        metavar="YOUTUBE_URL",
        help="Required YouTube URL, such as https://youtu.be/VIDEO_ID.",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        metavar="DIRECTORY",
        help="Required directory where the downloaded file will be saved. Created automatically if needed.",
    )
    parser.add_argument(
        "-f",
        "--format",
        default="mp4",
        choices=SUPPORTED_FORMATS,
        metavar="FORMAT",
        help="Output format: mp4 for video or mp3 for audio. Default: mp4.",
    )
    parser.add_argument(
        "--quality",
        default="best",
        choices=SUPPORTED_QUALITIES,
        metavar="QUALITY",
        help="MP4 quality preference: best, 1080p, 720p, or 480p. Ignored for MP3. Default: best.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files instead of resuming or skipping them.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show detailed diagnostic output and raw tracebacks for failures.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Optional sequence of argument strings. When ``None``, argparse
            reads arguments from ``sys.argv``.

    Returns:
        Parsed ``argparse.Namespace`` with URL, output, format, quality,
        overwrite, and verbose fields.

    Raises:
        SystemExit: If argparse detects a malformed command.
    """
    parser = create_parser()
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the py-yt-video-downloader CLI.

    Args:
        argv: Optional command-line argument sequence excluding the program name.
            When ``None``, arguments are read from ``sys.argv``.

    Returns:
        Process exit code: ``0`` on success, ``1`` for expected runtime failures,
        and ``2`` for malformed commands handled by argparse.

    Raises:
        SystemExit: Propagated only from argparse for malformed commands or
            ``--help``/``--version`` requests.
    """
    args = parse_args(argv)

    try:
        request = build_request(
            url=args.url,
            output=args.output,
            format_name=args.format,
            quality=args.quality,
            overwrite=args.overwrite,
            verbose=args.verbose,
        )
        download(request)
    except DownloaderError as exc:
        _print_friendly_error(exc)
        if args.verbose:
            traceback.print_exc()
        return 1
    except Exception:
        # Unexpected bugs are hidden by default so users are not confronted with raw internals.
        print("Unexpected error: the download could not be completed.", file=sys.stderr)
        print("Tip: Re-run with --verbose to see technical details for bug reports.", file=sys.stderr)
        if args.verbose:
            traceback.print_exc()
        return 1

    return 0


def _print_friendly_error(error: DownloaderError) -> None:
    """Print a concise user-facing error and optional troubleshooting tip.

    Args:
        error: Expected project exception containing a message and optional tip.

    Returns:
        None.
    """
    print(f"Error: {error.message}", file=sys.stderr)
    if error.tip:
        print(f"Tip: {error.tip}", file=sys.stderr)
    print("\nTry one of these examples:", file=sys.stderr)
    print(EXAMPLES, file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
